/**
 * The upload-purpose catalogue (feature 016, roadmap 4.9 — research R11, FR-002/FR-003).
 *
 * ── Why a catalogue and not parameters ───────────────────────────────────────────────────────────
 * Closed and additive, the same discipline as the permission catalogue (011), the automation-trigger
 * catalogue (014) and the audit-action catalogue (015). Every member has a reason to exist and an
 * unknown member resolves to NOTHING — there is no permissive default anywhere in this file, because
 * a default is how a purpose nobody reviewed gets a size cap nobody chose.
 *
 * ── This file is the whole of FR-003 ─────────────────────────────────────────────────────────────
 * Adding a consumer means adding a ROW here. No validation code branches on a purpose name, and
 * `libs/common/src/uploads/second-purpose.spec.ts` asserts that as a scan over the validation path
 * rather than trusting it as a style preference. ADR 0035's avatar limits are a row, which is
 * exactly the claim the ADR made when it said the avatar waits for this feature.
 *
 * ── Where the permission comes from ──────────────────────────────────────────────────────────────
 * A purpose NAMES an existing key from the feature-011 catalogue; this feature introduces no new
 * permission. `permission: null` is explicit and means "authenticated is sufficient" — never "no
 * check". Setting your own avatar is a self-service profile action, and the consumer at 8.10
 * enforces "your own profile"; inventing a `crm.avatar.upload` key would be a key with one holder,
 * everyone.
 */
import { isRasterImage, type DetectableContentType } from './content-type';
import { EXPORT_ARTEFACT_TTL_SECONDS } from '../exports/scopes';

/**
 * Whether the ingest path stores a small re-encoded copy alongside the original.
 *
 * `never`       — no derivative, ever (a purpose that carries no images).
 * `images-only` — a derivative for the image types in the list; the non-image ones simply have none.
 * `always`      — the same runtime behaviour, plus a CLAIM about the catalogue: every type this
 *                 purpose allows is an image, so "no derivative" cannot happen. The claim is not
 *                 decoration — `purposes.spec.ts` fails the build if an `always` purpose ever gains
 *                 a non-image type, which is the review moment that would otherwise be silent.
 */
export type DerivativePolicy = 'never' | 'images-only' | 'always';

/**
 * Where the bytes came from — added by feature 017 (roadmap 4.10, research R5).
 *
 * `ingested` — supplied by someone else. The type is decided by MAGIC BYTES against the closed
 *              detection table, because a declared type and a filename are inputs to a lie.
 * `produced` — generated by this product (an export artefact). There is no declared type to
 *              disbelieve, and the format (CSV) has no magic number, so the check inverts: the
 *              content must be valid UTF-8 **and** must match NONE of the binary signatures.
 *
 * This fact exists so `content-type.ts` did not have to change. Adding `text/csv` to the detection
 * table would have turned the allow-list from *formats we can verify* into *formats we accept on
 * faith* — and that faith-based type would then be reachable from any future untrusted-ingest
 * purpose, which is a real weakening of feature 016 to solve a problem provenance already answers.
 */
export type UploadOrigin = 'ingested' | 'produced';

export interface UploadPurpose {
  /** An existing feature-011 permission key, or null = authenticated is sufficient (never "no check"). */
  readonly permission: string | null;
  /** Untrusted input, or something we made? Decides HOW content is validated (017 / R5). */
  readonly origin: UploadOrigin;
  /**
   * Whether the bytes of this purpose may EVER be deleted (feature 017 / research R8).
   *
   * `false` for everything ingested. `true` only for an artefact whose defining property is that it
   * expires — and even then the deletion is reachable only as a system actor through
   * `UsersMaintenanceService`, never as a user-facing verb: feature 016's "no UpdateUpload /
   * DeleteUpload on the uploads surface" still holds.
   *
   * ⚠️ An `ingested` purpose must NEVER be `ephemeral` — that pairing is what would delete an avatar
   * in active use. `purposes.spec.ts` fails the build on it.
   */
  readonly ephemeral: boolean;
  /**
   * Seconds until an EPHEMERAL purpose's bytes may be purged; 0 for everything else (feature 017 / R7).
   *
   * On the row rather than derived from the purpose's name, because nothing in this product may branch on
   * a catalogue key's spelling — a rule the purpose tests already enforce for validation and now for
   * lifetime too.
   */
  readonly ttlSeconds: number;
  /** Refused above this, before the whole file has been accepted (FR-007). */
  readonly maxBytes: number;
  /** Closed allow-list, by CONTENT (FR-005/FR-006). SVG is absent from every list, by construction. */
  readonly types: readonly DetectableContentType[];
  readonly derivative: DerivativePolicy;
  /** Longest edge of the derivative, in pixels. Data, so no code decides a size per purpose. */
  readonly derivativeLongestEdge: number;
}

const MB = 1024 * 1024;

export const UPLOAD_PURPOSES = {
  /**
   * A file an agent attaches to a conversation message (this feature's only live consumer).
   * Gated by the reply permission itself: attaching to a reply is part of replying, so it needs no
   * key of its own (spec Assumptions). PNG/JPEG/WebP/GIF/PDF is what a support conversation actually
   * carries — screenshots and receipts. Office documents and archives are deliberately absent: a
   * container format that nothing inspects is a permitted type in name only.
   */
  message_attachment: {
    permission: 'crm.conversation.reply',
    origin: 'ingested',
    ephemeral: false,
    ttlSeconds: 0,
    maxBytes: 10 * MB,
    types: ['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'application/pdf'],
    derivative: 'images-only',
    derivativeLongestEdge: 256,
  },

  /**
   * A file that arrived ON a channel (feature 033, roadmap 6.1/6.4 — subpoint 2.1a/2.1c).
   *
   * ── Why its own row rather than reusing `message_attachment` ─────────────────────────────────────
   * The writer is not a person. `message_attachment` is gated on `crm.conversation.reply` because an
   * agent attaching a file is exercising an authority; an inbound file is written by the intake path on
   * behalf of a stranger, and there is no operator whose permission could be checked. Reusing that row
   * would silently give a stranger's upload an agent's caps and an agent's permission story.
   *
   * `permission: null` therefore means **"the caller is the intake path, not an authenticated human"**,
   * which is a different statement from the avatar's "authenticated is sufficient". Neither means "no
   * check": intake is reached only through a verified channel signature or the mailbox we hold, and
   * that verification IS the authorization for this write.
   *
   * ── The caps are deliberately tighter than an agent's ───────────────────────────────────────────
   * 5 MB rather than 10, and no GIF. This is the one upload path an unauthenticated party can reach, so
   * the budget is what a support conversation actually needs — a screenshot or a receipt — and nothing
   * more. A stranger cannot use it to park 10 MB of animation in our storage.
   *
   * ⚠️ A rejected file MUST NOT cost its message. FR-018 requires the words to land even when the
   * attachment does not, because a customer's text silently lost to a bad file is indistinguishable
   * from the system working. That rule lives in the intake path, not in this row; the row only decides
   * what is acceptable.
   */
  channel_inbound_attachment: {
    permission: null,
    origin: 'ingested',
    ephemeral: false,
    ttlSeconds: 0,
    maxBytes: 5 * MB,
    types: ['image/png', 'image/jpeg', 'image/webp', 'application/pdf'],
    derivative: 'images-only',
    derivativeLongestEdge: 256,
  },

  /**
   * The profile avatar. Limits fixed by ADR 0035 (2 MB; PNG/JPEG/WebP by content; SVG excluded) —
   * reproduced here as data, which is the FR-003/SC-009 claim being made rather than described.
   *
   * ⚠️ BINDING NOTE FOR ROADMAP 8.10 — the avatar consumer MUST claim its upload.
   * Nothing claims it today, so an avatar registered through this purpose stays `pending` forever.
   * A future reclaim job (ADR 0015) collects `pending` uploads, and would therefore delete avatars
   * that are in active use. Cheap to write down now; silent data loss to discover later.
   */
  avatar: {
    permission: null,
    origin: 'ingested',
    ephemeral: false,
    ttlSeconds: 0,
    maxBytes: 2 * MB,
    types: ['image/png', 'image/jpeg', 'image/webp'],
    derivative: 'always',
    derivativeLongestEdge: 256,
  },

  /**
   * A produced export artefact (feature 017, roadmap 4.10 — research R4/R5/R8).
   *
   * The row that lets an export reach storage **through the existing `CreateUpload`**, so `users`
   * remains the only holder of storage credentials and feature 016's structural guarantee passes
   * unchanged — no new `bytes` message, no second writer, no presign.
   *
   * `types` is EMPTY on purpose, and it is not an oversight: the detection table is the allow-list for
   * INGESTED content, and this purpose is `produced`, so the type is not decided by matching a
   * signature. Validation for a produced artefact is the inverse check (valid UTF-8, matching no
   * binary signature) and lives in `services/users/src/uploads`. An empty list here means "no
   * ingested type is acceptable for this purpose", which is exactly right — a user cannot upload INTO
   * the export purpose, and a test asserts the gateway's multipart route cannot reach it.
   *
   * `ephemeral: true` is the only `true` in this file. It is what makes the 24-hour purge legal, and
   * the purge is what makes expiry a deletion rather than a flag (SEC-27).
   */
  conversation_export: {
    permission: 'crm.exports.conversations',
    origin: 'produced',
    ephemeral: true,
    ttlSeconds: EXPORT_ARTEFACT_TTL_SECONDS,
    maxBytes: 10 * MB,
    types: [],
    derivative: 'never',
    derivativeLongestEdge: 0,
  },
} as const satisfies Record<string, UploadPurpose>;

export type UploadPurposeName = keyof typeof UPLOAD_PURPOSES;

/** Every registered purpose name. The catalogue is closed: this is the complete set. */
export const UPLOAD_PURPOSE_NAMES = Object.keys(UPLOAD_PURPOSES) as UploadPurposeName[];

/**
 * The purposes whose bytes may EVER be deleted — the purge predicate's whole input (feature 017 / R8).
 *
 * DERIVED, not listed. That is the entire point: the one path in this product that removes stored bytes
 * asks the catalogue which rows it is allowed to touch, so an avatar or an attachment is unreachable
 * from it **by construction** rather than by a hard-coded exclusion somebody has to maintain. Making a
 * purpose deletable means setting `ephemeral: true` on its row, in review, next to the reason.
 */
export const EPHEMERAL_PURPOSE_NAMES: readonly UploadPurposeName[] = UPLOAD_PURPOSE_NAMES.filter(
  (name) => UPLOAD_PURPOSES[name].ephemeral,
);

export function isUploadPurpose(value: string | undefined): value is UploadPurposeName {
  return !!value && Object.prototype.hasOwnProperty.call(UPLOAD_PURPOSES, value);
}

/**
 * The catalogue entry for `value`, or `null` when the purpose does not exist.
 *
 * `null` is the refusal (FR-002). Every caller must treat it as one — there is deliberately no
 * `?? DEFAULT_PURPOSE` anywhere, because a fallback here would hand an unreviewed upload the most
 * permissive limits in the catalogue.
 */
export function purposeOf(value: string | undefined): UploadPurpose | null {
  if (!isUploadPurpose(value)) return null;
  return UPLOAD_PURPOSES[value];
}

/** True iff `contentType` is on this purpose's allow-list. */
export function purposeAllowsType(purpose: UploadPurpose, contentType: string): boolean {
  return (purpose.types as readonly string[]).includes(contentType);
}

/**
 * Whether a derivative is produced for an accepted file of `contentType` under `purpose`.
 * Reads the catalogue and the type; names no purpose (SC-009).
 */
export function shouldProduceDerivative(purpose: UploadPurpose, contentType: string): boolean {
  if (purpose.derivative === 'never') return false;
  return isRasterImage(contentType);
}
